Homework 2
================
Zhiquan Chen

# Problem 1

``` r
subway_raw =
  read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(
      .default = col_character(),
      `Station Latitude` = col_double(),
      `Station Longitude` = col_double(),
      ADA = col_logical()
    )
  ) |>
clean_names()
subway_df =
  subway_raw |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    starts_with("route"),
    entry,
    vending,
    entrance_type,
    ada
  ) |>
  mutate(
    entry = entry == "YES"
  )
```

This dataset records subway entrances and exits in NYC. After cleaning,
it contains 1868 rows and 19 columns, including line, station name,
station coordinates, routes served, entry permission, vending
availability, entrance type, and ADA compliance. I standardized the
column names, retained the requested variables, explicitly specified
data types, and converted entry from “YES”/“NO” to TRUE/FALSE. No
entrance/exit records were removed. The data are not yet tidy for
route-level analysis because route names are stored in eleven separate
columns, route1 through route11, instead of a single route-name column.

``` r
n_stations =
  subway_df |>
  distinct(line, station_name) |>
  nrow()
n_stations
```

    ## [1] 465

There are 465 distinct stations.

``` r
n_ada_stations =
  subway_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
n_ada_stations
```

    ## [1] 84

84 stations are ADA compliant.

``` r
no_vending_summary =
  subway_df |>
  filter(vending == "NO") |>
  summarise(
    n_no_vending = n(),
    n_allow_entry = sum(entry),
    prop_allow_entry = mean(entry)
  )

no_vending_summary
```

    ## # A tibble: 1 × 3
    ##   n_no_vending n_allow_entry prop_allow_entry
    ##          <int>         <int>            <dbl>
    ## 1          183            69            0.377

37.70% of station entrances / exits without vending allow entrance.

``` r
subway_long =
  subway_df |>
  pivot_longer(
    cols = starts_with("route"),
    names_to = "route_number",
    names_prefix = "route",
    names_transform = list(route_number = as.integer),
    values_to = "route_name",
    values_drop_na = TRUE
  )
```

``` r
n_a_stations =
  subway_long |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()

n_a_stations
```

    ## [1] 60

60 distinct stations serve the A train.

``` r
n_a_ada_stations =
  subway_long |>
  filter(
    route_name == "A",
    ada == TRUE
  ) |>
  distinct(line, station_name) |>
  nrow()

n_a_ada_stations
```

    ## [1] 17

17 of the stations that serve the A train are ADA compliant.

# Problem 2

``` r
trash_path = "data/202509 Trash Wheel Collection Data.xlsx"

mr_trash_df =
  read_excel(
    trash_path,
    sheet = "Mr. Trash Wheel",
    range = "A2:N710"
  ) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    dumpster = as.integer(dumpster),
    month = str_to_title(str_trim(month)),
    year = as.integer(year),
    date = as.Date(date),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )

professor_trash_df =
  read_excel(
    trash_path,
    sheet = "Professor Trash Wheel",
    range = "A2:M135"
  ) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    dumpster = as.integer(dumpster),
    month = str_to_title(str_trim(month)),
    year = as.integer(year),
    date = as.Date(date),
    trash_wheel = "Professor Trash Wheel"
  )

gwynnda_trash_df =
  read_excel(
    trash_path,
    sheet = "Gwynns Falls Trash Wheel",
    range = "A2:L352"
  ) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    dumpster = as.integer(dumpster),
    month = str_to_title(str_trim(month)),
    year = as.integer(year),
    date = as.Date(date),
    trash_wheel = "Gwynnda"
  )

trash_df =
  bind_rows(
    mr_trash_df,
    professor_trash_df,
    gwynnda_trash_df
  )
```

``` r
professor_summary =
  trash_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarise(
    total_weight_tons = sum(weight_tons, na.rm = TRUE)
  )

professor_summary$total_weight_tons
```

    ## [1] 282.26

``` r
gwynnda_june_2022_summary =
  trash_df |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  summarise(
    n_records = n(),
    total_cigarette_butts = sum(cigarette_butts, na.rm = TRUE)
  )

gwynnda_june_2022_summary
```

    ## # A tibble: 1 × 2
    ##   n_records total_cigarette_butts
    ##       <int>                 <dbl>
    ## 1        13                 18120

The combined dataset contains 1188 dumpster-level observations and 15
variables: 707 observations from Mr. Trash Wheel, 132 from Professor
Trash Wheel, and 349 from Gwynnda. Key variables include the source
trash wheel, dumpster identifier, month, year, collection date, weight
in tons, volume in cubic yards, and recorded counts of items such as
plastic bottles, cigarette butts, and sports balls. I restricted each
import to the relevant table range, standardized variable names and
month labels, removed rows without dumpster identifiers, made year and
date types consistent, and rounded Mr. Trash Wheel’s sports-ball counts
to the nearest integer before converting them to integer type. A source
variable identifies the trash wheel for each observation. Missing
measurements and variables absent from individual sheets are retained as
NA, not zero. For the available data, Professor Trash Wheel collected
282.26 tons of trash, and Gwynnda collected 18,120 cigarette butts in
June 2022.

# Problem 3

``` r
baseline_raw =
  read_csv(
    "data/data_mci/MCI_baseline.csv",
    skip = 1,
    na = c("", "NA", "."),
    col_types = cols(
      .default = col_double(),
      ID = col_integer()
    )
  ) |>
  clean_names() |>
  rename(baseline_age = current_age) |>
  mutate(
    sex = factor(
      sex,
      levels = c(0, 1),
      labels = c("Female", "Male")
    ),
    apoe4 = factor(
      apoe4,
      levels = c(0, 1),
      labels = c("Non-carrier", "Carrier")
    )
  )
```

``` r
baseline_excluded =
  baseline_raw |>
  filter(
    !is.na(age_at_onset),
    age_at_onset <= baseline_age
  )

baseline_excluded |>
  select(id, baseline_age, age_at_onset)
```

    ## # A tibble: 4 × 3
    ##      id baseline_age age_at_onset
    ##   <int>        <dbl>        <dbl>
    ## 1    72         62.9         62.5
    ## 2   234         66.7         66.7
    ## 3   283         69           68.3
    ## 4   380         70.3         70.2

``` r
baseline_df =
  baseline_raw |>
  filter(
    is.na(age_at_onset) | age_at_onset > baseline_age
  )
```
